### ISSUE TITLE
nama web apps?

### ISSUE THREAD

**Issue by DimasInchidi** [DimasInchidi/KarETaPe#2]
nama sebelemunya kan EKAtepe, mau diganti kah?
sementara aku ambil karetape tapi belum fix
kalo ok aja karetape index tolong diganti ya
kalo di welcome (dashboard) ada juga ganti juga byar ga ambigu

**Comment by kid5234** [comment]
KareTaPe ? gitu?

**Comment by DimasInchidi** [comment]
iya boleh, ato cari nama lain dulu?

**Comment by DimasInchidi** [comment]
done by @kid5234
